### PR TITLE
Correction from Yves Lin.  I have no way to proofread it.  Bas?

### PR DESCRIPTION
**Pull request by SabotagePerformanceAppraisals**
Hi MJ,

Sorry there were some typos found, please use this as the latest.  Thank you.

Thank You and Best Regards

Yves Lin

### CODE REVIEW

**Comment by basvodde** [comment]
Bas? Should I merge it?

**Comment by SabotagePerformanceAppraisals** [comment]
I’m wondering if you can check it, as I have no clue with Chinese.  But it’s not mainland Chinese, so I don’t know whether you can read it.

**Comment by basvodde** [comment]
Ah no. I would be a bad proof reader ;)

**Comment by terryyin** [comment]
where's the Chinese?

**Comment by tcmak** [comment]
Terry, it's the in the PDF file.

As far as I notice, most of the changes related to using the Chinese terms
instead of English terms (or supplemented with the original English terms).
So for example on page 2, "待辦事項" now comes with its English name
"待辦事項（Item）"

**Pull request merged**
